import Vditor from "vditor";
import "vditor/src/assets/scss/index.scss"
Vue.use(Vditor);
export const vditor=new Vditor("vditor", {
    //4.刚刚声明的变量contentEditor被赋值为一个Vditor实例,
    height: 500,
    placeholder: "此处为话题内容……",
    theme: "classic",
    counter: {
      enable: true,
      type: "markdown",
    },
    preview: {
      delay: 0,
      hljs: {
        style: "monokai",
        lineNumber: true,
      },
    },
    tab: "\t",
    typewriterMode: true,
    toolbarConfig: {
      pin: true,
    },
    cache: {
      enable: false,
    },
    mode: "sv",
    toolbar: [
      "emoji",
      "headings",
      "bold",
      "italic",
      "strike",
      "link",
      "|",
      "list",
      "ordered-list",
      "check",
      "outdent",
      "indent",
      "|",
      "quote",
      "line",
      "code",
      "inline-code",
      "insert-before",
      "insert-after",
      "|",
      // 'record',
      "table",
      "|",
      "undo",
      "redo",
      "|",
      "edit-mode",
      // 'content-theme',
      "code-theme",
      "export",
      {
        name: "more",
        toolbar: ["fullscreen", "both", "preview", "info", "help"],
      },
    ],
  });
